<?php
namespace php\awt;

/**
 * Class RenderingHints
 * @package php\awt
 */
class RenderingHints
{
    const KEY_ANTIALIASING = 1;
    const VALUE_ANTIALIAS_ON = 21;
    const VALUE_ANTIALIAS_OFF = 22;
    const VALUE_ANTIALIAS_DEFAULT = 23;

    const KEY_RENDERING = 2;
    const VALUE_RENDER_SPEED = 24;
    const VALUE_RENDER_QUALITY = 25;
    const VALUE_RENDER_DEFAULT = 26;

    const KEY_DITHERING = 3;
    const VALUE_DITHER_DISABLE = 27;
    const VALUE_DITHER_ENABLE = 28;
    const VALUE_DITHER_DEFAULT = 29;

    const KEY_TEXT_ANTIALIASING = 4;
    const VALUE_TEXT_ANTIALIAS_ON = 30;
    const VALUE_TEXT_ANTIALIAS_OFF = 31;
    const VALUE_TEXT_ANTIALIAS_DEFAULT = 32;
    const VALUE_TEXT_ANTIALIAS_GASP = 33;
    const VALUE_TEXT_ANTIALIAS_LCD_HRGB = 34;
    const VALUE_TEXT_ANTIALIAS_LCD_HBGR = 35;
    const VALUE_TEXT_ANTIALIAS_LCD_VRGB = 36;
    const VALUE_TEXT_ANTIALIAS_LCD_VBGR = 37;

    const KEY_TEXT_LCD_CONTRAST = 5;

    const KEY_FRACTIONALMETRICS = 6;
    const VALUE_FRACTIONALMETRICS_OFF = 38;
    const VALUE_FRACTIONALMETRICS_ON = 39;
    const VALUE_FRACTIONALMETRICS_DEFAULT = 40;

    const KEY_INTERPOLATION = 7;
    const VALUE_INTERPOLATION_NEAREST_NEIGHBOR = 41;
    const VALUE_INTERPOLATION_BILINEAR = 42;
    const VALUE_INTERPOLATION_BICUBIC = 43;

    const KEY_ALPHA_INTERPOLATION = 8;
    const VALUE_ALPHA_INTERPOLATION_SPEED = 44;
    const VALUE_ALPHA_INTERPOLATION_QUALITY = 45;
    const VALUE_ALPHA_INTERPOLATION_DEFAULT = 46;

    const KEY_COLOR_RENDERING = 9;
    const VALUE_COLOR_RENDER_SPEED = 47;
    const VALUE_COLOR_RENDER_QUALITY = 48;
    const VALUE_COLOR_RENDER_DEFAULT = 49;

    const KEY_STROKE_CONTROL = 10;
    const VALUE_STROKE_DEFAULT = 50;
    const VALUE_STROKE_NORMALIZE = 51;
    const VALUE_STROKE_PURE = 52;
}